import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { getCurrentUser } from "@/lib/auth";
import { ChatProvider } from "@/components/chat/ChatProvider";
import ChatDock from "@/components/chat/ChatDock";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // relu à chaque router.refresh() (login / logout) : le provider sait qui est connecté
  const user = await getCurrentUser();

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <ChatProvider userId={user?.id ?? null}>
          {children}
          {/* le chat en bas à droite, sur toutes les pages */}
          <ChatDock />
        </ChatProvider>
      </body>
    </html>
  );
}
