Include /etc/nginx/modsecurity.conf
SecRuleEngine On
Include /etc/modsecurity/crs/crs-setup.conf
SecAction "id:900001,phase:1,pass,nolog,t:none,setvar:tx.allowed_methods=GET HEAD POST OPTIONS PUT PATCH DELETE"
SecAction "id:900000,phase:1,pass,nolog,t:none,setvar:tx.paranoia_level=2"
Include /usr/share/modsecurity-crs/rules/*.conf
SecRuleUpdateTargetById 941320 "!ARGS:json.content"
SecRuleUpdateTargetById 941100 "!ARGS:json.content"
SecRuleUpdateTargetById 942130 "!ARGS:json.content"
SecRuleUpdateTargetById 931130 "!ARGS:iss"
