"use client";

import { useState } from "react";
import { apiClient } from "@/lib/apiClient";

interface TwoFactorSectionProps {
  enabled: boolean;
  onChanged?: (enabled: boolean) => void;
}

export default function TwoFactorSection({
  enabled,
  onChanged,
}: TwoFactorSectionProps) {
  const [setup, setSetup] = useState<{
    otpauthUrl: string;
    qrCode: string;
  } | null>(null);

  const [showDisable, setShowDisable] = useState(false);

  const [code, setCode] = useState("");
  const [password, setPassword] = useState("");

  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const [message, setMessage] = useState("");

  async function handleStartSetup() {
    setLoading(true);
    setError("");
    setMessage("");

    try {
      const response = await apiClient.twoFactor.setup();

      if (!response.success) {
        setError(response.error ?? "Failed to start 2FA setup.");
        return;
      }

      setSetup(response.data);
      setCode("");
    } catch {
      setError("Unable to connect to the server.");
    } finally {
      setLoading(false);
    }
  }

  async function handleEnable() {
    setLoading(true);
    setError("");
    setMessage("");

    try {
      const response = await apiClient.twoFactor.enable(code);

      if (!response.success) {
        setError(response.error ?? "Invalid authentication code.");
        return;
      }

      setSetup(null);
      setCode("");
      setMessage("Two-factor authentication has been enabled.");
      onChanged?.(true);
    } catch {
      setError("Unable to connect to the server.");
    } finally {
      setLoading(false);
    }
  }

  async function handleDisable() {
    setLoading(true);
    setError("");
    setMessage("");

    try {
      const response = await apiClient.twoFactor.disable(password, code);

      if (!response.success) {
        setError(response.error ?? "Failed to disable 2FA.");
        return;
      }

      setPassword("");
      setCode("");
      setShowDisable(false);
      setMessage("Two-factor authentication has been disabled.");
      onChanged?.(false);
    } catch {
      setError("Unable to connect to the server.");
    } finally {
      setLoading(false);
    }
  }

  function cancelSetup() {
    setSetup(null);
    setCode("");
    setError("");
    setMessage("");
  }

  function cancelDisable() {
    setShowDisable(false);
    setPassword("");
    setCode("");
    setError("");
    setMessage("");
  }

  function openDisable() {
    setShowDisable(true);
    setPassword("");
    setCode("");
    setError("");
    setMessage("");
  }

  return (
    <section className="section-divider mt-6 border-t pt-4">
      {setup ? (
        /* -------------------- SETUP 2FA -------------------- */
        <div>
          <p className="text-sm font-medium">
            Set up your authenticator
          </p>

          <p className="mt-1 text-xs text-muted-foreground">
            Scan this QR code with Google Authenticator, Microsoft
            Authenticator, Authy, or another TOTP-compatible app.
          </p>

          <div className="mt-4 flex justify-center">
            <img
              src={setup.qrCode}
              alt="Two-factor authentication QR code"
              className="h-48 w-48 border border-border p-2"
            />
          </div>

          <p className="mt-4 text-center text-xs text-muted-foreground">
            After scanning the QR code, enter the 6-digit code generated by
            your authenticator app.
          </p>

          <div className="mx-auto mt-4 flex max-w-sm flex-col gap-3">
            <input
              type="text"
              inputMode="numeric"
              maxLength={6}
              value={code}
              onChange={(e) =>
                setCode(e.target.value.replace(/\D/g, "").slice(0, 6))
              }
              placeholder="123456"
              className="field-input text-center tracking-widest"
              autoFocus
            />

            <button
              type="button"
              onClick={handleEnable}
              disabled={loading || code.length !== 6}
              className="btn-nav justify-center disabled:opacity-50"
            >
              {loading ? "Verifying..." : "Enable 2FA"}
            </button>

            <button
              type="button"
              onClick={cancelSetup}
              disabled={loading}
              className="btn-nav justify-center"
            >
              Cancel
            </button>
          </div>

          <details className="mt-4">
            <summary className="cursor-pointer text-xs text-muted-foreground">
              Can't scan the QR code?
            </summary>

            <p className="mt-2 break-all text-xs text-muted-foreground">
              {setup.otpauthUrl}
            </p>
          </details>
        </div>
      ) : showDisable ? (
        /* -------------------- DISABLE 2FA -------------------- */
        <div>
          <div className="flex items-center justify-between gap-4">
            <div>
              <p className="text-sm font-medium">
                Disable two-factor authentication
              </p>

              <p className="mt-1 text-xs text-muted-foreground">
                Enter your password and current authenticator code.
              </p>
            </div>
          </div>

          <div className="mt-4 grid grid-cols-1 gap-3 sm:grid-cols-2">
            <input
              type="password"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              placeholder="Current password"
              autoComplete="current-password"
              className="field-input"
              autoFocus
            />

            <input
              type="text"
              inputMode="numeric"
              maxLength={6}
              value={code}
              onChange={(e) =>
                setCode(e.target.value.replace(/\D/g, "").slice(0, 6))
              }
              placeholder="6-digit authenticator code"
              className="field-input"
            />
          </div>

          <div className="mt-3 flex justify-end gap-2">
            <button
              type="button"
              onClick={cancelDisable}
              disabled={loading}
              className="btn-nav"
            >
              Cancel
            </button>

            <button
              type="button"
              onClick={handleDisable}
              disabled={
                loading ||
                code.length !== 6 ||
                password.length === 0
              }
              className="btn-nav disabled:opacity-50"
            >
              {loading ? "Disabling..." : "Confirm"}
            </button>
          </div>
        </div>
      ) : (
        /* -------------------- NORMAL STATE -------------------- */
        <div className="flex items-center justify-between gap-4">
          <div>
            {enabled ? (
              <>
                <p className="text-sm font-medium">
                  Two-factor authentication is enabled.
                </p>

                <p className="mt-1 text-xs text-muted-foreground">
                  You will need your authenticator code when signing in.
                </p>
              </>
            ) : (
              <>
                <p className="text-sm font-medium">
                  Two-factor authentication is not enabled.
                </p>

                <p className="mt-1 text-xs text-muted-foreground">
                  Protect your account with a time-based authentication code.
                </p>
              </>
            )}
          </div>

          {enabled ? (
            <button
              type="button"
              onClick={openDisable}
              disabled={loading}
              className="btn-nav shrink-0"
            >
              Disable 2FA
            </button>
          ) : (
            <button
              type="button"
              onClick={handleStartSetup}
              disabled={loading}
              className="btn-nav shrink-0 disabled:opacity-50"
            >
              {loading ? "Starting setup..." : "Enable 2FA"}
            </button>
          )}
        </div>
      )}

      {error ? (
        <p className="mt-4 form-error">
          {error}
        </p>
      ) : null}

      {message ? (
        <p className="mt-4 text-sm text-muted-foreground">
          {message}
        </p>
      ) : null}
    </section>
  );
}