services:


  postgresql:
    build:
      context: ./requirements/postgresql
    container_name: postgresql
    volumes: 
      - postgresql_data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - platform_network



  redis:
    build:
      context: ./requirements/redis
    container_name: redis
    volumes:
      - redis_data:/data
    restart: always
    networks:
      - platform_network

  backend:
    build:
      context: .
      dockerfile: ./requirements/backend/dockerfile
    container_name: backend
    env_file: 
      - .env
    depends_on:
      - postgresql
      - redis
    networks:
      - platform_network
  
  nextjs:
    build:
      context: .
      dockerfile: ./requirements/nextjs/dockerfile
    container_name: nextjs
    env_file:
      - .env
    volumes:
      - ./app:/app
      - nextjs_node_modules:/app/node_modules
    depends_on:
      - backend   
    ports:
      - "3000:3000"
    networks:
      - platform_network
    
  nginx:
    build:
      context: ./requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
    #volumes:
    #- postgresql_data:/var/www/html 
    depends_on:
      - nextjs
      - backend
    networks:
      - platform_network 

volumes:
  postgresql_data:
  redis_data:
  nextjs_node_modules:

networks:
  platform_network: