services:


  postgresql:
    build:
      context: ./requirements/postgresql
      dockerfile: dockerfile
    container_name: postgresql
    volumes: 
      - postgresql_data:/var/lib/postgresql/data
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 2s
      timeout: 3s
      retries: 10
    networks:
      - platform_network



  redis:
    build:
      context: ./requirements/redis
      dockerfile: dockerfile
    container_name: redis
    volumes:
      - redis_data:/data
    restart: always
    networks:
      - platform_network

  backend:
    build:
      context: .
      dockerfile: ./requirements/backend/dockerfile
    container_name: backend
    env_file: 
      - .env
    depends_on:
      postgresql:
        condition: service_healthy
      redis:
        condition: service_started
      vault-init:
        condition: service_completed_successfully
    networks:
      - platform_network
    environment:
      VAULT_ADDR: http://vault:8200
      VAULT_TOKEN_FILE: /vault-token/backend.token
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules
      - vault_token:/vault-token:ro
    ports:
    - "4000:4000"
    - "51212:51212"
  nextjs:
    build:
      context: .
      dockerfile: ./requirements/nextjs/dockerfile
    container_name: nextjs
    env_file:
      - .env
    volumes:
      - ./app:/app
      - nextjs_node_modules:/app/node_modules
    depends_on:
      - backend   
    ports:
      - "3000:3000"
    networks:
      - platform_network
    
  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: dockerfile
    container_name: nginx
    ports:
      - "8444:443"
    #volumes:
    #- postgresql_data:/var/www/html 
    depends_on:
      - nextjs
      - backend
    networks:
      - platform_network 

  backup:
    build:
      context: ./requirements/backup
    container_name: backup
    user: "1000:1000"
    env_file:
      - .env
    environment:
      PGHOST: postgresql
      PGUSER: ${POSTGRES_USER}
      PGPASSWORD: ${POSTGRES_PASSWORD}
      PGDATABASE: ${POSTGRES_DB}
    volumes:
      - ./backups:/backups
    depends_on:
      postgresql:
        condition: service_healthy
    restart: always
    networks:
      - platform_network

  vault:
    build:
      context: ./requirements/vault
    container_name: vault
    command: ["vault", "server", "-config=/vault/config"]
    volumes:
      - vault_data:/vault/file
    networks:
      - platform_network
    restart: always


  vault-init:
    build:
      context: ./requirements/vault
    container_name: vault-init
    command: ["sh", "/bootstrap.sh"]
    env_file:
      - .env
    volumes:
      - vault_keys:/keys
      - vault_token:/shared
    depends_on:
      - vault
    networks:
      - platform_network
    restart: "no"

volumes:
  postgresql_data:
  redis_data:
  nextjs_node_modules:
  backend_node_modules:
  vault_data:
  vault_keys:
  vault_token:
  
networks:
  platform_network: