FROM docker.io/library/debian:bookworm

RUN apt-get update && \
    apt-get install -y redis-server && \
    apt-get clean

COPY redis.conf /etc/redis/redis.conf

CMD ["redis-server", "/etc/redis/redis.conf"]