FROM node:22-bookworm

WORKDIR /app

COPY backend/package*.json ./

COPY backend/prisma ./prisma

RUN npm install

RUN npm install multer -D @types/multer

COPY backend/ ./

EXPOSE 4000

CMD ["sh", "-c", "npx prisma migrate deploy && npm run dev"]