FROM debian:bookworm

RUN apt-get update && apt-get install -y nginx \
                            openssl \
                            curl

COPY nginx.conf /etc/nginx/nginx.conf

RUN mkdir -p /etc/nginx/certs && \
    openssl req -x509 -nodes -days 365 \
    -newkey rsa:2048 \
    -keyout /etc/nginx/certs/localhost.key \
    -out /etc/nginx/certs/localhost.crt \
    -subj "/CN=localhost"

CMD ["nginx", "-g", "daemon off;"]